export default {
    products: [
        {
        _id: '1',
        name: 'Carrot',
        category: 'vagetable',
        image: '/images/carrot.jpg',
        price: 'Price-10',
        brand: 'Item-Vegetable',
        weight: 'Quantity-per piece',
        rating: 4.5,
        numReviews: '10',
    },
    {
        _id: '2',
        name: 'Mango',
        category: 'vagetable',
        image: '/images/mango.jpg',
        price: 'Price-110',
        brand: 'Item-Fruit',
        weight: 'Quantity-per KG',
        rating: 5.0,
        numReviews: '15',
    },
    {
        _id: '3',
        name: 'Hilsha Fish',
        category: 'vagetable',
        image: '/images/fish.jpg',
        price: 'Price-750',
        brand: 'Item-Fish',
        weight: 'Quantity-per piece',
        rating: 4.9,
        numReviews: '30',
    },
    {
        _id: '4',
        name: 'Deshi Chicken',
        category: 'vagetable',
        image: '/images/chicken.jpg',
        price: 'Price-220',
        brand: 'Item-Chicken',
        weight: 'Quantity-per piece',
        rating: 4.3,
        numReviews: '19',
    },
    {
        _id: '5',
        name: 'Broiler Egg',
        category: 'vagetable',
        image: '/images/egg.jpg',
        price: 'Price-7.5',
        brand: 'Item-Egg',
        weight: 'Quantity-per piece',
        rating: 4.6,
        numReviews: '22',
    },
    {
        _id: '6',
        name: 'White Rice',
        category: 'vagetable',
        image: '/images/white-rice.jpg',
        price: 'Price-55',
        brand: 'Item-Rice',
        weight: 'Quantity-per KG',
        rating: 5.5,
        numReviews: '55',
    },
    
]
}